feat:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/pages/**'
          - 'src/components/**'
          - 'src/features/**'
          - 'src/hooks/**'
          - 'src/services/**'

style:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.css'
          - 'src/constants/colors.ts'
          - 'src/constants/typography.ts'

test:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.test.ts'
          - 'src/**/*.test.tsx'
          - 'src/mocks/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'

chore:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'vite.config.ts'
          - 'tsconfig*.json'
          - '.eslintrc*'
          - 'eslint.config.*'
          - '.prettierrc*'
          - '.husky/**'
          - '.github/PULL_REQUEST_TEMPLATE.md'
